@Avaliacao_HostAddress = http://localhost:5221/api/usuarios
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdGVAZW1haWwuY29tIiwiZXhwIjoxNzQ2NDkyODA2fQ.MqD59Re3RhOHG5eDFrFmCXObu0z_qq6p58MiJw43hAs


### Listar todos users
GET {{Avaliacao_HostAddress}}/listar
Authorization: Bearer {{token}}
Content-Type: application/json

###

### Listar user
GET {{Avaliacao_HostAddress}}/listar/1
Content-Type: application/json

###

### CADASTRO
POST {{Avaliacao_HostAddress}}/cadastrar
Content-Type: application/json

{
  "email": "teste2@email.com",
  "senha": "12345"
}

###
### LOGIN
POST {{Avaliacao_HostAddress}}/login
Content-Type: application/json

{
  "email": "teste@email.com",
  "senha": "12345"
}

###
